server:
# 端口
  port: 8082

spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: utf-8
    password: ukewrjiohotrbbcf
    username: 694278550@qq.com
    port: 587
    # 设置开启ssl
    properties:
      mail:
        stmp:
          ssl:
            enable: true

  rabbitmq:
      username: guest
      password: guest
      host: 192.168.80.130
      port: 5672
      listener:
        simple:
          #开启手动确认
          acknowledge-mode: manual
  redis:
    #服务器地址
    host: 192.168.80.130
    #服务器端口
    port: 6379
    #服务器密码
    password: root
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5